SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `ARCHIVED_CN`
--

-- --------------------------------------------------------

--
-- 表的结构 `JOB`
--

CREATE TABLE IF NOT EXISTS `JOB` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `URL` varchar(4096) COLLATE utf8_unicode_ci NOT NULL,
  `UK` int(11) NOT NULL,
  `SUBMIT_TIME` timestamp NULL DEFAULT NULL,
  `SECONDS` int(6) NOT NULL COMMENT '间隔时间秒',
  `VALID` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`),
  KEY `VALID` (`VALID`,`UK`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- 表的结构 `TASK`
--

CREATE TABLE IF NOT EXISTS `TASK` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `URL` varchar(4096) COLLATE utf8_unicode_ci NOT NULL,
  `UK` int(11) NOT NULL COMMENT 'URL的标识符',
  `TITLE` varchar(4096) COLLATE utf8_unicode_ci NOT NULL,
  `MONTH_ID` int(4) NOT NULL,
  `DAY_ID` int(4) NOT NULL,
  `STATUS` int(2) NOT NULL DEFAULT '0' COMMENT '0: 未提交页面保存,1:提交呢,2:完成的',
  `RECORD_ID` int(11) DEFAULT '0' COMMENT 'API返回的ID值',
  `APPROVED` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已经人工确认过',
  `ENABLED` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否是可见的',
  `CREATE_TIME` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `MONTH_ID` (`MONTH_ID`,`APPROVED`,`ENABLED`,`STATUS`),
  KEY `DAY_ID` (`DAY_ID`,`APPROVED`,`ENABLED`,`STATUS`),
  KEY `UK` (`UK`,`STATUS`,`APPROVED`,`ENABLED`),
  KEY `STATUS` (`STATUS`,`APPROVED`,`ENABLED`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
